M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-26T21:58:36+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-26T21:58:36+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
%
G90
G05
T1
X2.8031Y-2.5669
X5.3465Y-4.5197
M30
