M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-26T21:59:01+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-26T21:59:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
%
G90
G05
T1
X4.6063Y-4.0748
X7.126Y-2.1457
M30
